/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package framespractice;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.NumberFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Prosper
 */
public class JuiceBar extends javax.swing.JFrame {

    NumberFormat nf = NumberFormat.getCurrencyInstance();
    int quantityv, clientv, juicev, smoothiesv;
    double pricev, costv, taxv, subtotal = 0, amtduev = 0, salesv = 0, extrav;

    /**
     * Creates new form JuiceBar
     */
    public JuiceBar() {
        initComponents();
        Dimension dm = Toolkit.getDefaultToolkit().getScreenSize();
        int x = dm.width / 2 - this.getWidth() / 2;
        int y = dm.height / 2 - this.getHeight() / 2;
        this.setLocation(x, y);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("crest.jpg")));
        this.setTitle("HTU Juice Bar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        juicesSelection = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        noSelection = new javax.swing.JRadioButton();
        fruitRadio = new javax.swing.JRadioButton();
        veggieRadio = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        strawRadio = new javax.swing.JRadioButton();
        pomeRadio = new javax.swing.JRadioButton();
        berryRadio = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        energyCheck = new javax.swing.JCheckBox();
        ladiesCheck = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cost = new javax.swing.JLabel();
        subTotal = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tax = new javax.swing.JLabel();
        amountDue = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        editQuantity = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        addToOrder = new javax.swing.JButton();
        orderComplete = new javax.swing.JButton();
        summeryReport = new javax.swing.JButton();
        newButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAutoscrolls(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanel3PropertyChange(evt);
            }
        });

        noSelection.setBackground(new java.awt.Color(255, 255, 255));
        juicesSelection.add(noSelection);
        noSelection.setText("No Selection");
        noSelection.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                noSelectionStateChanged(evt);
            }
        });

        fruitRadio.setBackground(new java.awt.Color(255, 255, 255));
        juicesSelection.add(fruitRadio);
        fruitRadio.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        fruitRadio.setText("Fruit");
        fruitRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fruitRadioActionPerformed(evt);
            }
        });

        veggieRadio.setBackground(new java.awt.Color(255, 255, 255));
        juicesSelection.add(veggieRadio);
        veggieRadio.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        veggieRadio.setText("Veggie");
        veggieRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veggieRadioActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Smoothies");
        jLabel4.setToolTipText("");

        strawRadio.setBackground(new java.awt.Color(255, 255, 255));
        juicesSelection.add(strawRadio);
        strawRadio.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        strawRadio.setText("Strawberry");
        strawRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strawRadioActionPerformed(evt);
            }
        });

        pomeRadio.setBackground(new java.awt.Color(255, 255, 255));
        juicesSelection.add(pomeRadio);
        pomeRadio.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        pomeRadio.setText("Pomegranate");
        pomeRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pomeRadioActionPerformed(evt);
            }
        });

        berryRadio.setBackground(new java.awt.Color(255, 255, 255));
        juicesSelection.add(berryRadio);
        berryRadio.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        berryRadio.setText("Wheat Berry");
        berryRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                berryRadioActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Juices");
        jLabel3.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(noSelection)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(strawRadio)
                            .addComponent(pomeRadio)
                            .addComponent(berryRadio)
                            .addComponent(jLabel4))))
                .addGap(0, 24, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(fruitRadio)
                    .addComponent(veggieRadio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(noSelection)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fruitRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(veggieRadio)
                .addGap(31, 31, 31)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pomeRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(strawRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(berryRadio)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Extra - 5.00 Each");
        jLabel5.setToolTipText("");

        energyCheck.setBackground(new java.awt.Color(255, 255, 255));
        energyCheck.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        energyCheck.setText("Energy Booster");
        energyCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                energyCheckActionPerformed(evt);
            }
        });

        ladiesCheck.setBackground(new java.awt.Color(255, 255, 255));
        ladiesCheck.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        ladiesCheck.setText("For The Ladies");
        ladiesCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ladiesCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(energyCheck)
                    .addComponent(jLabel5)
                    .addComponent(ladiesCheck))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(energyCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ladiesCheck)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setText("Price: ");

        price.setBackground(new java.awt.Color(255, 255, 255));
        price.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        price.setForeground(new java.awt.Color(255, 187, 52));
        price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        price.setText("0.00");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel8.setText("Quantity:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel10.setText("Cost");

        cost.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        cost.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cost.setText("$0.00");

        subTotal.setBackground(new java.awt.Color(255, 187, 52));
        subTotal.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        subTotal.setForeground(new java.awt.Color(152, 203, 2));
        subTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subTotal.setText("$0.00");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel13.setText("Sub Total");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel14.setText("Tax (3.5%)");

        tax.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tax.setText("$0.00");

        amountDue.setBackground(new java.awt.Color(255, 187, 52));
        amountDue.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        amountDue.setForeground(new java.awt.Color(152, 203, 2));
        amountDue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        amountDue.setText("$0.00");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel17.setText("Amount Due:");

        editQuantity.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        editQuantity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        editQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                editQuantityKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel17))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(editQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(subTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(amountDue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(price))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(editQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cost))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(subTotal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(tax))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(amountDue))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setText("HTU Juice Bar");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        addToOrder.setBackground(new java.awt.Color(98, 0, 239));
        addToOrder.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        addToOrder.setForeground(new java.awt.Color(255, 255, 258));
        addToOrder.setText("ADD TO ORDER");
        addToOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToOrderActionPerformed(evt);
            }
        });

        orderComplete.setBackground(new java.awt.Color(98, 0, 239));
        orderComplete.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        orderComplete.setForeground(new java.awt.Color(255, 255, 255));
        orderComplete.setText("ORDER COMPLETE");
        orderComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderCompleteActionPerformed(evt);
            }
        });

        summeryReport.setBackground(new java.awt.Color(98, 0, 239));
        summeryReport.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        summeryReport.setForeground(new java.awt.Color(255, 255, 255));
        summeryReport.setText("SUMMERY REPORT");
        summeryReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                summeryReportActionPerformed(evt);
            }
        });

        newButton.setBackground(new java.awt.Color(98, 0, 239));
        newButton.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        newButton.setForeground(new java.awt.Color(255, 255, 255));
        newButton.setText("NEW");
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });

        exitButton.setBackground(new java.awt.Color(98, 0, 239));
        exitButton.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 255, 255));
        exitButton.setText("EXIT");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(newButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitButton))
                    .addComponent(summeryReport, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderComplete, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addToOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(addToOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(orderComplete, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(summeryReport, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newButton, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framespractice/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(80, 80, 80))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        noSelection.setSelected(true);
        editQuantity.grabFocus();
        editQuantity.setText("1");
        orderComplete.setEnabled(false);
        summeryReport.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        editQuantity.setText("1");
        editQuantity.grabFocus();
        energyCheck.setSelected(false);
        ladiesCheck.setSelected(false);
        cost.setText("$0.00");
        tax.setText("$0.00");
        subTotal.setText("$0.00");
        amountDue.setText("$0.00");
        orderComplete.setEnabled(false);
        addToOrder.setEnabled(true);
        noSelection.setSelected(true);
        
    }//GEN-LAST:event_newButtonActionPerformed

    private void orderCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderCompleteActionPerformed
        if (noSelection.isSelected()) {
            salesv += amtduev;
            clientv++;
            subtotal = 0;
            amtduev = 0;
            summeryReport.setEnabled(true);
            addToOrder.setEnabled(false);
            addToOrder.setEnabled(false);
        } else {
            if (JOptionPane.showConfirmDialog(rootPane, "Add this frink?", "Order Complete", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                addToOrder.doClick();
            }
            salesv += amtduev;
            clientv++;
            subtotal = 0;
            amtduev = 0;
            summeryReport.setEnabled(true);
            addToOrder.setEnabled(false);
            addToOrder.setEnabled(false);
        }
    }//GEN-LAST:event_orderCompleteActionPerformed

    private void summeryReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_summeryReportActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Clients Served - " + clientv +
                "\nJuice bought - " + juicev + "\nSmothies bought - " + smoothiesv +
                "\nTotal Sales - " + nf.format(salesv));
    }//GEN-LAST:event_summeryReportActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        if (JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to exit?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE) == 0) {
            System.exit(0);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Continue ordering");
        }
    }//GEN-LAST:event_exitButtonActionPerformed

    private void jPanel3PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanel3PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3PropertyChange

    private void fruitRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fruitRadioActionPerformed
        if (fruitRadio.isSelected()) {
            price.setText("7.00");
            updateCost();
        }
    }//GEN-LAST:event_fruitRadioActionPerformed

    private void veggieRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veggieRadioActionPerformed
        if (veggieRadio.isSelected()) {
            price.setText("5.00");
            updateCost();
        }
    }//GEN-LAST:event_veggieRadioActionPerformed

    private void pomeRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pomeRadioActionPerformed
        if (pomeRadio.isSelected()) {
            price.setText("10.00");
            updateCost();
        }
    }//GEN-LAST:event_pomeRadioActionPerformed

    private void strawRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strawRadioActionPerformed
        if (strawRadio.isSelected()) {
            price.setText("13.00");
            updateCost();
        }
    }//GEN-LAST:event_strawRadioActionPerformed

    private void berryRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_berryRadioActionPerformed
        if (berryRadio.isSelected()) {
            price.setText("15.50");
            updateCost();
        }
    }//GEN-LAST:event_berryRadioActionPerformed

    private void noSelectionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_noSelectionStateChanged
        if (noSelection.isSelected()) {
            price.setText("0.00");
            updateCost();
        }
    }//GEN-LAST:event_noSelectionStateChanged

    private void updateCost() {
        if (editQuantity.getText().length() != 0) {
            pricev = Double.parseDouble(price.getText());
            quantityv = Integer.parseInt(editQuantity.getText());
            costv = (pricev * quantityv) + extrav;
            cost.setText(nf.format(costv));
        }
    }

    private void energyCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_energyCheckActionPerformed
        if (energyCheck.isSelected()) {
            extrav += 5.00;
            updateCost();
        } else {
            extrav -= 5.00;
            updateCost();
        }
    }//GEN-LAST:event_energyCheckActionPerformed

    private void ladiesCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ladiesCheckActionPerformed
        if (ladiesCheck.isSelected()) {
            extrav += 5.00;
            updateCost();
        } else {
            extrav -= 5.00;
            updateCost();
        }
    }//GEN-LAST:event_ladiesCheckActionPerformed

    private void addToOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToOrderActionPerformed
        try {
            if (noSelection.isSelected() == true) {
                JOptionPane.showMessageDialog(rootPane, "Select a drink");
            } else {
                subtotal += costv;
                taxv = 0.035 * subtotal;
                amtduev = subtotal + taxv;
                subTotal.setText(nf.format(subtotal));
                tax.setText(nf.format(taxv));
                amountDue.setText(nf.format(amtduev));

                // Not juice
                if (fruitRadio.isSelected() == true || veggieRadio.isSelected() == true) {
                    juicev += quantityv;
                    orderComplete.setEnabled(true);
                } else {
                    smoothiesv += quantityv;
                    //reset
                    energyCheck.setSelected(false);
                    ladiesCheck.setSelected(false);
                    extrav = 0;
                    noSelection.setSelected(true);
                    editQuantity.setText("1");
                    orderComplete.setEnabled(true);
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.toString());
        }
    }//GEN-LAST:event_addToOrderActionPerformed

    private void editQuantityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editQuantityKeyReleased
        updateCost();
    }//GEN-LAST:event_editQuantityKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JuiceBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JuiceBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JuiceBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JuiceBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JuiceBar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToOrder;
    private javax.swing.JLabel amountDue;
    private javax.swing.JRadioButton berryRadio;
    private javax.swing.JLabel cost;
    private javax.swing.JTextField editQuantity;
    private javax.swing.JCheckBox energyCheck;
    private javax.swing.JButton exitButton;
    private javax.swing.JRadioButton fruitRadio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.ButtonGroup juicesSelection;
    private javax.swing.JCheckBox ladiesCheck;
    private javax.swing.JButton newButton;
    private javax.swing.JRadioButton noSelection;
    private javax.swing.JButton orderComplete;
    private javax.swing.JRadioButton pomeRadio;
    private javax.swing.JLabel price;
    private javax.swing.JRadioButton strawRadio;
    private javax.swing.JLabel subTotal;
    private javax.swing.JButton summeryReport;
    private javax.swing.JLabel tax;
    private javax.swing.JRadioButton veggieRadio;
    // End of variables declaration//GEN-END:variables
}
