/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package framespractice;

import java.time.LocalDate;
import java.util.Date;

/**
 *
 * @author Prosper
 */
public class PensionEstimator extends javax.swing.JFrame {

    /**
     * Creates new form PensionEstimator
     */
    public PensionEstimator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rPNDC = new javax.swing.JRadioButton();
        rAct = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        fNumberOfMonths = new javax.swing.JTextField();
        fNumberOfMonths.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fNumberOfMonthsFocusLost(evt);
            }
        });
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fYear1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fYear2 = new javax.swing.JTextField();
        fYear3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        display = new javax.swing.JTextArea();
        bReset = new javax.swing.JButton();
        bEstimate = new javax.swing.JButton();
        fDateOfBirth = new javax.swing.JTextField();
        fDateOfRet = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel1.setText("Pension Estimator");

        jLabel2.setText("Date Of Birth:");

        jLabel3.setText("Date Of Retrement:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pension Scheme"));

        buttonGroup1.add(rPNDC);
        rPNDC.setText("PNDC Law 247");
        rPNDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rPNDCActionPerformed(evt);
            }
        });

        buttonGroup1.add(rAct);
        rAct.setText("Act 766");
        rAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rActActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rPNDC)
                .addGap(22, 22, 22)
                .addComponent(rAct)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rPNDC)
                    .addComponent(rAct))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jLabel4.setText("Number Of Minths Contributed:");

        jLabel5.setText("Three (3) Best Years Salaries:");

        jLabel6.setText("Year 1:");

        jLabel7.setText("Year 2:");

        jLabel8.setText("Year 3:");

        display.setColumns(20);
        display.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        display.setRows(5);
        display.setText("Average");
        jScrollPane1.setViewportView(display);

        bReset.setText("Reset");
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });

        bEstimate.setText("Estimate");
        bEstimate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEstimateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 70, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fNumberOfMonths)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(fYear1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(fYear2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(fYear3))
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bReset, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bEstimate, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fDateOfRet))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fDateOfBirth)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fDateOfRet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fNumberOfMonths, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fYear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(fYear2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(fYear3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bEstimate, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        bResetActionPerformed(null);
    }//GEN-LAST:event_formWindowOpened

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
     fNumberOfMonths.setText("");
     display.setText("");
     LocalDate ld = LocalDate.now();
     String n = ld.toString();
     fDateOfBirth.setText(n);
     fDateOfRet.setText(n);
     rAct.setSelected(true);
     fYear1.setText("0.00");
     fYear2.setText("0.00");
     fYear3.setText("0.00");
    }//GEN-LAST:event_bResetActionPerformed

    private void bEstimateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEstimateActionPerformed
        // Estimate button logic: parse inputs, calculate, and display results
        try {
            // Parse date of birth and retirement date
            LocalDate dob = LocalDate.parse(fDateOfBirth.getText().trim());
            LocalDate dor = LocalDate.parse(fDateOfRet.getText().trim());

            // Parse number of months contributed
            int months = Integer.parseInt(fNumberOfMonths.getText().trim());

            // Parse the three best years' salaries
            double yr1 = Double.parseDouble(fYear1.getText().trim());
            double yr2 = Double.parseDouble(fYear2.getText().trim());
            double yr3 = Double.parseDouble(fYear3.getText().trim());

            // Create MyRetirement object
            MyRetirement retire = new MyRetirement(yr1, yr2, yr3, dob, dor, months);

            // Calculate values
            double avgSalary = retire.averagesalary();
            int retireAge = retire.retireage();
            double annualPension = retire.annualpension();
            double monthlyPension = retire.monthlypension();
            double pensionRight = retire.pensionright();

            // Build result message
            StringBuilder sb = new StringBuilder();
            sb.append("Retirement Age: ").append(retireAge).append(" years\n");
            sb.append("Average Salary: ").append(String.format("%.2f", avgSalary)).append("\n");
            sb.append("Annual Pension: ").append(String.format("%.2f", annualPension)).append("\n");
            sb.append("Monthly Pension: ").append(String.format("%.2f", monthlyPension)).append("\n");
            sb.append("Pension Right: ").append(String.format("%.2f", pensionRight)).append("%\n");

            // Show results in a message dialog
            javax.swing.JOptionPane.showMessageDialog(this, sb.toString(), "Pension Estimate", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            // Show any exception in a message dialog
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bEstimateActionPerformed

    private void rPNDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rPNDCActionPerformed
        // PNDC Law 247 radio button checked change event
        validatePensionQualification("PNDC Law 247", 240);
    }//GEN-LAST:event_rPNDCActionPerformed

    private void rActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rActActionPerformed
        // Act 766 radio button checked change event
        validatePensionQualification("Act 766", 180);
    }//GEN-LAST:event_rActActionPerformed

    /**
     * Validates pension qualification based on selected scheme
     * @param schemeName Name of the pension scheme
     * @param requiredMonths Minimum months required for full pension
     */
    private void validatePensionQualification(String schemeName, int requiredMonths) {
        try {
            // Check if months contributed textbox is not empty
            String monthsText = fNumberOfMonths.getText().trim();
            if (!monthsText.isEmpty()) {
                int months = Integer.parseInt(monthsText);
                
                // Parse date of birth to calculate age
                LocalDate dob = LocalDate.parse(fDateOfBirth.getText().trim());
                LocalDate currentDate = LocalDate.now();
                int age = currentDate.getYear() - dob.getYear();
                
                // Check if contributor qualifies for full pension
                boolean qualifiesForFullPension = (age >= 55) && (months >= requiredMonths);
                
                if (!qualifiesForFullPension) {
                    // Show message and focus on months textbox
                    String message = "You do not qualify for full pension under " + schemeName + ".\n";
                    message += "Requirements: Age 55+ and " + requiredMonths + " months minimum contribution.\n";
                    message += "Your age: " + age + " years, Months contributed: " + months;
                    
                    javax.swing.JOptionPane.showMessageDialog(this, message, "Pension Qualification", javax.swing.JOptionPane.WARNING_MESSAGE);
                    fNumberOfMonths.requestFocus();
                }
            }
        } catch (Exception ex) {
            // Show any exception in a message dialog
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Validation Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void fNumberOfMonthsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fNumberOfMonthsFocusLost
        // Leave event for number of months contributed textbox
        // Call validation for both pension schemes
        if (rPNDC.isSelected()) {
            validatePensionQualification("PNDC Law 247", 240);
        } else if (rAct.isSelected()) {
            validatePensionQualification("Act 766", 180);
        }
    }//GEN-LAST:event_fNumberOfMonthsFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PensionEstimator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PensionEstimator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PensionEstimator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PensionEstimator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PensionEstimator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEstimate;
    private javax.swing.JButton bReset;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextArea display;
    private javax.swing.JTextField fDateOfBirth;
    private javax.swing.JTextField fDateOfRet;
    private javax.swing.JTextField fNumberOfMonths;
    private javax.swing.JTextField fYear1;
    private javax.swing.JTextField fYear2;
    private javax.swing.JTextField fYear3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rAct;
    private javax.swing.JRadioButton rPNDC;
    // End of variables declaration//GEN-END:variables
}
